#!/bin/bash
#
# Copy this file to /etc/libvirt/hooks, make sure it's called "qemu".
# After this file is installed, restart libvirt.service.
# From now on, you can easily add per-guest qemu hooks.
# Add your hooks in /etc/libvirt/hooks/qemu.d/domain_name/hook_name/state_name.
# For a list of available hooks, please refer to https://www.libvirt.org/hooks.html
#
set +H
set -e

DOMAIN_NAME="$1"
HOOK_NAME="$2"
STATE_NAME="$3"
MISC=("${@:4}")

BASEDIR="$(dirname "$0")"

HOOKPATH="${BASEDIR}/qemu.d/${DOMAIN_NAME}/${HOOK_NAME}/${STATE_NAME}"

if [[ -f "${HOOKPATH}" ]]; then
    "${HOOKPATH}" "$@"
elif [[ -d "${HOOKPATH}" ]]; then
    while read -r file; do
        # check for null string
        [[ -n "${file}" ]] &&
            ${file} "$@"
    done <<<"$(find -L "${HOOKPATH}" -maxdepth 1 -type f -executable -print)"
fi
